"""
Roman Urdu Sentiment Dataset Generator
Creates a labeled dataset of Roman Urdu social media text samples.
Classes: Positive, Negative, Neutral
"""

import pandas as pd
import random

# Realistic Roman Urdu social media text samples
positive_samples = [
    "yeh bohot acha product hai mujhe pasand aya",
    "main bohot khush hun aaj ka din bohot acha raha",
    "kya zabardast match tha bilkul kamaal",
    "bohot maza aya aaj party mein",
    "yeh movie bohot achi thi must watch",
    "Allah ka shukar hai sab theek hai",
    "best restaurant hai yeh try karo zaroor",
    "bohot pyara hai yeh bachcha mashallah",
    "result acha aya alhamdulillah",
    "yeh game bohot fun hai khelo zaroor",
    "kya baat hai bhai kamaal kar diya",
    "bohot talented hai yeh banda respect",
    "mujhe yeh jagah bohot pasand hai",
    "aaj ka khana bohot tasty tha",
    "bohot helpful log hain yahan ke",
    "exam acha gaya mera inshallah pass",
    "yeh gaana bohot hit hai sunna chahiye",
    "dil khush hogaya yeh dekh ke",
    "amazing quality hai is product ki",
    "bohot supportive hai yeh teacher",
    "kya shandar performance thi waah",
    "acha laga sun ke bohot khushi hui",
    "yeh phone bohot fast hai love it",
    "great work bhai keep it up",
    "mujhe aaj promotion mili alhamdulillah",
    "bohot pyari jagah hai visit karo",
    "yeh course bohot informative tha",
    "best decision tha yeh lena",
    "bohot acchi service hai recommend karta hun",
    "mashallah bohot talented lagte ho",
    "is dukan ka khana bohot fresh hai",
    "yeh laptop bohot smooth chalta hai",
    "kya zabardast goal tha shandar",
    "mujhe bohot maza aya concert mein",
    "bohot acha insaan hai dil ka saaf",
    "yeh deal bohot sasti hai grab karo",
    "main bohot motivated feel kar raha hun",
    "camera quality outstanding hai is phone ki",
    "bohot pyara design hai love it",
    "bilkul perfect hai yeh mere liye",
    "kya lajawab taste hai yeh",
    "family ke saath acha waqt guzara",
    "yeh app bohot useful hai download karo",
    "sab log bohot cooperative the",
    "mujhe yeh rang bohot pasand hai",
    "interview acha gaya positive vibes",
    "kya behtareen quality hai is brand ki",
    "bohot lucky feel kar raha hun aaj",
    "yeh jagah bohot peaceful hai",
    "zabardast batting ki usne kya player hai",
    "bohat acha experience tha overall",
    "khana bohat lazeez tha maza aa gaya",
    "is hotel ki service best hai",
    "aaj bohat productive din tha",
    "yeh dress bohat pyari lag rahi hai",
    "staff bohat friendly tha",
    "delivery bohat fast aayi impressed",
    "kya kamaal ki painting hai wow",
    "bohat achi book hai must read",
    "aaj mood bohat acha hai",
    "yeh teacher bohat well explain karte hain",
    "meri team ne bohat acha kiya proud",
    "yeh perfume ki smell bohat achi hai",
    "hospital mein treatment bohat acha mila",
    "bohat acha lagta hai yeh sunke",
    "party mein bohat enjoy kiya",
    "yeh scheme bohat faydemand hai",
    "salary increase hogayi bohot khush hun",
    "yeh shoes bohot comfortable hain",
    "exam clear hogaya first attempt mein",
    "bohot mast weather hai aaj",
    "is university ka environment bohot acha hai",
    "coding seekh raha hun bohot maza aa raha",
    "mera best friend bohot loyal hai",
    "yeh series bohot interesting hai binge watch karo",
    "prize jeet liya bohot proud feel",
    "yeh car bohot smooth chalti hai",
    "biryani bohot lajawab thi aaj",
    "sunset bohot beautiful tha aaj",
    "gym jaana start kiya feeling great",
    "project complete hogaya on time relief",
    "teacher ne appreciate kiya feel good",
    "naya phone liya bohot khush hun",
    "dost se milke bohot acha laga",
    "marks ache aaye family khush hai",
    "morning walk pe gaya fresh feel",
    "yeh chai bohot zabardast hai",
    "flight on time aayi smooth journey",
    "internship mil gayi excited hun",
    "aaj cricket khela bohot maza aya",
    "yeh course free hai aur bohot acha",
    "sab theek hogaya tension khatam",
    "bohot pyari smile hai tumhari",
    "naya ghar liya bohot khushi hai",
    "health improve horahi hai daily exercise se",
    "yeh painting bohot creative hai",
    "apna business start kiya feeling proud",
    "aaj bohot positive energy mil rahi hai",
    "yeh vlog bohot entertaining tha",
    "new year new goals excited hun",
]

negative_samples = [
    "yeh product bekaar hai waste of money",
    "bohot bura experience tha never again",
    "service bohot ghatiya hai complain karunga",
    "kya bakwas movie thi time waste",
    "bohot disappoint hua main yeh dekh ke",
    "paise barbaad hogaye is pe",
    "yeh dukan wala fraud hai dhoka deta hai",
    "bohot boring tha yeh program",
    "quality bohot kharab hai mat lena",
    "bohot ganda khana tha yahan ka",
    "delivery mein bohot delay hua fed up",
    "customer service worst hai bilkul",
    "yeh phone hang hota hai bara",
    "bohot rude staff hai is jagah ka",
    "result kharab aya bohot tension hai",
    "yeh cheez toot gayi ek din mein",
    "pura din barbaad hogaya is ki wajah se",
    "bohot mehnga hai aur quality zero",
    "koi madad nahi karta yahan",
    "bohot ghatiya management hai",
    "exam mein fail hogaya bohot bura laga",
    "yeh app crash hota hai baar baar",
    "refund nahi milta fraud company hai",
    "traffic mein phanse hue hain bohot irritation",
    "bohot unfair decision tha yeh",
    "health kharab hai bohot pareshan hun",
    "is jagah jaana galti thi",
    "yeh banda bohot fake hai trust mat karo",
    "packaging toot ke aayi bohot careless",
    "internet speed bohot slow hai worst isp",
    "yeh scam hai paisa mat lagao",
    "team haar gayi bohot dukh hua",
    "puri raat neend nahi aayi tension ki wajah se",
    "bohot ganda mausam hai bahar mat jao",
    "is company mein kaam karna mushkil hai",
    "bohot mehnga bill aaya bijli ka",
    "yeh dawai kaam nahi kar rahi",
    "transport bohot kharab hai yahan",
    "bhai ne dhoka diya vishwas toot gaya",
    "salary delay ho rahi hai bohot frustration",
    "exam bohot mushkil tha kuch samajh nahi aya",
    "yeh brand overrated hai bilkul",
    "bohot thak gaya hun aaj kaam karke",
    "rent bohot zyada hai afford nahi hota",
    "yeh plan change kiya unhone bina bataye",
    "fever aur sir dard bohot zyada hai",
    "parking nahi milti yahan kabhi",
    "bohot ghatiya attitude hai is ki",
    "paise doob gaye investment mein",
    "yeh course scam hai kuch nahi sikhate",
    "bohat buri halat hai sadak ki",
    "yeh network hamesha down rehta hai",
    "complaint ki lekin koi response nahi",
    "bohat mushkil hai yeh sab handle karna",
    "manager bohat rude hai kaam nahi kar sakte",
    "ac kharab hogaya garmi mein mar rahe hain",
    "paani ka masla bohat serious hai yahan",
    "load shedding se tang aa gaye",
    "mobile chori hogaya bohat nuqsaan hua",
    "doctor ne galat medicine di worse hogaya",
    "assignment reject hogaya dobara karna padega",
    "dost ne paise wapas nahi kiye",
    "interview mein reject hogaya hopeless feel",
    "yeh restaurant overpriced hai bohot",
    "presentation mein bohot nervous tha flop hogaya",
    "laptop kharab hogaya data chala gaya",
    "barish mein ghar mein paani aa gaya",
    "bus late aayi class miss hogayi",
    "wifi bohot slow hai kuch load nahi hota",
    "pet kharab hai khana hazam nahi hota",
    "marks bohot kam aaye regret hai",
    "fine lag gaya traffic police ne",
    "project mein bugs bohot hain fix nahi hote",
    "bohot akela feel ho raha hai",
    "ghar walon se jhagda hogaya",
    "yeh sim ki calls drop hoti hain",
    "mood bohot kharab hai aaj",
    "headphones toot gaye ek hafte mein",
    "parhai mein dil nahi lagta",
    "loan ka installment miss hogaya",
    "yeh warranty fake nikli scam",
    "uber ne zyada charge kiya",
    "sardi mein heater kaam nahi karta",
    "cricket team ki bowling bohot weak hai",
    "yeh game pay to win hai unfair",
    "friend zone hogaya bohot sad",
    "is area mein bijli bohot jati hai",
    "coding mein error aa raha fix nahi ho raha",
    "yeh movie ki story predictable thi boring",
    "subah se sir dard hai medicine bhi nahi",
    "bohot time waste hua is meeting mein",
    "ghar ki safai karne ka mann nahi",
    "rent increase hogaya dobara shift hona padega",
    "aaj bura din tha sab galat hua",
    "scholarship nahi mili bohot mehnat ki thi",
    "freelancing mein client ne payment nahi ki",
    "yeh scheme pagal banati hai logon ko",
    "anxiety bohot zyada hai kal exam hai",
    "order cancel hogaya bina wajah",
    "yeh teacher partial hai unfair marking",
]

neutral_samples = [
    "kal university jana hai class hai",
    "aaj mausam thanda hai bahar",
    "meeting 3 baje hai office mein",
    "market se saman lana hai ghar ke liye",
    "parso exam hai preparation karni hai",
    "aaj monday hai kaam pe jana hai",
    "yeh kitne ki hai puchna hai",
    "kal doctor ke paas jana hai checkup",
    "bus abhi aayi hai chalo chalte hain",
    "yeh form fill karna hai deadline hai",
    "ghar pe khana banana hai aaj",
    "library mein study karni hai",
    "assignment submit karna hai friday tak",
    "office se 6 baje niklunga",
    "kal flight hai islamabad ki",
    "yeh link share karo group mein",
    "parking yahan available hai",
    "registration date 15 may hai",
    "yeh road construction chal rahi hai",
    "school ke result aaj aaye hain",
    "petrol ki qeemat badli hai",
    "yeh naya store khula hai area mein",
    "kal sunday hai chutti hai",
    "pharmacy se medicine leni hai",
    "phone charge pe lagao battery low hai",
    "rent due date agle hafte hai",
    "cv update karna hai job ke liye",
    "aaj raat ko match hai 8 baje",
    "uber book karo jaana hai",
    "yeh file download ho rahi hai",
    "semester finals june mein hain",
    "naya update aaya hai phone mein",
    "traffic signal pe ruko abhi red hai",
    "passport renew karwana hai",
    "gym ka timing kya hai",
    "aaj grocery shopping karni hai",
    "project ki deadline next week hai",
    "interview kal subah 10 baje hai",
    "bill pay karna hai last date hai",
    "yeh formula yaad karna hai exam ke liye",
    "documents ready rakhna office ke liye",
    "metro station yahan se paas hai",
    "wifi ka password kya hai",
    "class cancel hogayi aaj teacher nahi aye",
    "courier aaya hai neeche jaake lelo",
    "sim ki validity check karo",
    "meeting reschedule hogayi kal pe",
    "paper pattern change hua hai is baar",
    "canteen mein chai available hai",
    "library 9 se 5 tak khuli hai",
    "yeh software install karna hai laptop mein",
    "kal se ramzan shuru hai",
    "election ki date announce hogayi",
    "admission last date 30 june hai",
    "parking charges 50 rupee hain",
    "ac ka remote kahan hai dhundo",
    "kal convocation hai university mein",
    "naya semester august mein shuru hoga",
    "lab mein experiment karna hai aaj",
    "presentation kal deni hai slides ready hain",
    "hostel mein mess ka khana milta hai",
    "sports day next month hai",
    "marksheet collect karni hai office se",
    "yeh software ka trial version hai",
    "attendance kam hai warning aayi",
    "campus mein wifi available hai",
    "kal holiday hai eid ki chutti",
    "practical exam next week hai",
    "thesis submission date december hai",
    "canteen mein paratha milta hai",
    "shuttle service 8 baje hai",
    "mid term exams october mein hain",
    "society mein event plan ho raha hai",
    "admission form online bharna hai",
    "transport fee 5000 hai semester ki",
    "orientation week mein session hoga",
    "id card banwana hai naya",
    "hostel room allot hua hai",
    "semester break july mein hai",
    "certificate verify karwana hai HEC se",
    "bank account kholna hai scholarship ke liye",
    "teacher ne assignment de diya hai",
    "lecture notes share karo group mein",
    "yeh book library mein available hai",
    "campus interview next friday hai",
    "summer classes mein enroll karna hai",
    "fyp topic select karna hai",
    "lab report submit karni hai kal",
    "grading policy change hui hai is semester",
    "student portal pe result upload hua",
    "society ka budget approve hua",
    "hostel mess timing change hui hai",
    "library card renew karwana hai",
    "scholarship form ki deadline parso hai",
    "exam hall mein seating arrangement lagi hai",
    "new timetable issue hua hai",
    "campus mein construction chal rahi hai",
    "convocation rehearsal kal hai",
    "clearance form submit karna hai",
    "alumni meetup next sunday hai",
]

def create_dataset():
    data = []
    
    for text in positive_samples:
        data.append({"text": text, "sentiment": "Positive"})
    for text in negative_samples:
        data.append({"text": text, "sentiment": "Negative"})
    for text in neutral_samples:
        data.append({"text": text, "sentiment": "Neutral"})
    
    df = pd.DataFrame(data)
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)
    
    print(f"Dataset created: {len(df)} samples")
    print(f"Distribution:\n{df['sentiment'].value_counts()}")
    
    df.to_csv("dataset/roman_urdu_sentiment.csv", index=False)
    return df

if __name__ == "__main__":
    import os
    os.makedirs("dataset", exist_ok=True)
    create_dataset()
